"use client";

import { useLanguage } from "./LanguageContext";

const en = {
  // Common
  back: "← Back",
  yes: "Yes",
  no: "No",
  federalState: "Federal state",
  purchasePrice: "Purchase price",
  notaryDate: "Notary appointment date",
  selectState: "Select a state…",

  // Home — hero
  homeEyebrow: "After mortgage approval",
  homeHeadingPre: "Your guide to the",
  homeHeadingHighlight: "6 weeks",
  homeHeadingSuffix: "that follow",
  homeDescription:
    "Mortgage approved — congratulations. Now comes the part no one explains: notary appointments, payment requests, official letters in German. We've got you.",

  // Home — feature cards
  card1Title: "Smart timeline",
  card1Description:
    "Personalised week-by-week checklist of everything after signing",
  card2Title: "Check a letter",
  card2Description:
    "Upload any payment request — we'll tell you if it looks legitimate",

  // Home — cost estimator
  estimatorTitle: "Closing Cost Estimator",
  maklerRow: "Maklergebühr (if applicable)",
  totalRow: "Total (incl. Makler)",
  estimatorNote:
    "Grunderwerbsteuer rate varies by state. Notarkosten and Grundbucheintrag are approximate. Maklergebühr is typically split equally between buyer and seller.",

  // Timeline — form
  timelineEyebrow: "Smart Timeline",
  timelineHeading: "Your personalised closing checklist",
  timelineDescription:
    "Tell us a few details and we'll build a week-by-week plan tailored to your situation.",
  maklerLabel: "Using a Makler (estate agent)?",
  lifeInsuranceLabel: "Life insurance required by lender?",
  specialContextLabel: "Anything unusual about your situation?",
  optional: "(optional)",
  specialContextPlaceholder:
    "e.g. buying with a non-EU partner, new build not yet finished, self-employed income",
  generateButton: "Generate my timeline",

  // Timeline — result
  timelineResultHeading: "Your closing plan",
  aiLoading: "✦ Personalising for your situation...",
  aiDone: "✦ Personalised for your situation · Generated by AI",

  // Validator — form
  validatorEyebrow: "Letter checker",
  validatorHeadingPre: "Is this payment request",
  validatorHeadingHighlight: "legitimate?",
  validatorDescription:
    "Upload any invoice or payment request you received. We'll check it against what's expected in a German property closing.",
  dropZoneTitle: "Drop your file here, or click to browse",
  dropZoneSubtitle: "PDF, JPG or PNG · max 10 MB",
  changeFile: "Click to change file",
  accuracyExpander: "Improve accuracy — add your property context",
  purchasePriceEur: "Purchase price (€)",
  maklerQuestion: "Did you use an estate agent?",
  pricePlaceholder: "e.g. 450000",
  checkButton: "Check this letter",
  checkingLabel: "Checking…",
  securityNote: "Your file is sent securely to Claude AI and is not stored.",

  // Validator — result
  checkAnother: "← Check another",
  offerBanner:
    "This appears to be an offer, not an invoice. You are not obligated to pay.",
  whatWeChecked: "What we checked",
  amountLabel: "Amount",
  whatToDoNext: "What to do next",
  selfVerify: "You should always verify too",
  disclaimerPrefix: "Disclaimer:",
  disclaimerBody:
    "This analysis is AI-generated and informational only. It is not legal or financial advice. When in doubt, consult your notary or a qualified professional before making any payment.",
  checkAnotherButton: "Check another letter",
  refetching: "Updating for new language…",

  // Verdict labels
  verdictLegitimate: "Looks legitimate",
  verdictSuspicious: "Something looks off",
  verdictUnclear: "Cannot determine",

  // Confidence labels
  confidenceHigh: "High confidence",
  confidenceMedium: "Medium confidence",
  confidenceLow: "Low confidence",
} as const;

const de: { [K in keyof typeof en]: string } = {
  // Common
  back: "← Zurück",
  yes: "Ja",
  no: "Nein",
  federalState: "Bundesland",
  purchasePrice: "Kaufpreis",
  notaryDate: "Notartermin",
  selectState: "Bundesland wählen…",

  // Home — hero
  homeEyebrow: "Nach der Finanzierungszusage",
  homeHeadingPre: "Ihr Leitfaden für die",
  homeHeadingHighlight: "6 Wochen",
  homeHeadingSuffix: "danach",
  homeDescription:
    "Finanzierung genehmigt — herzlichen Glückwunsch. Jetzt folgt der Teil, den niemand erklärt: Notartermine, Zahlungsaufforderungen, amtliche Briefe auf Deutsch. Wir begleiten Sie.",

  // Home — feature cards
  card1Title: "Zeitplan",
  card1Description:
    "Personalisierte Woche-für-Woche-Checkliste nach der Unterzeichnung",
  card2Title: "Brief prüfen",
  card2Description:
    "Laden Sie eine Zahlungsaufforderung hoch — wir prüfen, ob sie legitim ist",

  // Home — cost estimator
  estimatorTitle: "Kaufnebenkosten-Rechner",
  maklerRow: "Maklergebühr (falls zutreffend)",
  totalRow: "Gesamt (inkl. Makler)",
  estimatorNote:
    "Die Grunderwerbsteuer variiert je nach Bundesland. Notarkosten und Grundbucheintrag sind Näherungswerte. Die Maklergebühr wird üblicherweise zwischen Käufer und Verkäufer geteilt.",

  // Timeline — form
  timelineEyebrow: "Zeitplan",
  timelineHeading: "Ihr personalisierter Abschlussplan",
  timelineDescription:
    "Geben Sie einige Details ein und wir erstellen einen wöchentlichen Plan für Ihre Situation.",
  maklerLabel: "Makler beauftragt?",
  lifeInsuranceLabel: "Risikolebensversicherung erforderlich?",
  specialContextLabel: "Besonderheiten bei Ihrer Situation?",
  optional: "(optional)",
  specialContextPlaceholder:
    "z. B. Kauf mit nicht-EU-Partner, Neubau noch nicht fertiggestellt, Selbstständigkeit",
  generateButton: "Zeitplan erstellen",

  // Timeline — result
  timelineResultHeading: "Ihr Abschlussplan",
  aiLoading: "✦ Wird für Ihre Situation personalisiert…",
  aiDone: "✦ Für Ihre Situation personalisiert · Erstellt mit KI",

  // Validator — form
  validatorEyebrow: "Briefprüfer",
  validatorHeadingPre: "Ist diese Zahlungsaufforderung",
  validatorHeadingHighlight: "legitim?",
  validatorDescription:
    "Laden Sie eine erhaltene Rechnung oder Zahlungsaufforderung hoch. Wir prüfen sie gegen das, was bei einem deutschen Immobilienkauf üblich ist.",
  dropZoneTitle: "Datei hier ablegen oder klicken zum Auswählen",
  dropZoneSubtitle: "PDF, JPG oder PNG · max. 10 MB",
  changeFile: "Zum Ändern klicken",
  accuracyExpander: "Genauigkeit verbessern — Immobiliendaten hinzufügen",
  purchasePriceEur: "Kaufpreis (€)",
  maklerQuestion: "Haben Sie einen Makler beauftragt?",
  pricePlaceholder: "z. B. 450000",
  checkButton: "Brief prüfen",
  checkingLabel: "Wird geprüft…",
  securityNote:
    "Ihre Datei wird sicher an Claude KI übermittelt und nicht gespeichert.",

  // Validator — result
  checkAnother: "← Weiteren Brief prüfen",
  offerBanner:
    "Dies scheint ein Angebot zu sein, keine Rechnung. Sie sind nicht zur Zahlung verpflichtet.",
  whatWeChecked: "Was wir geprüft haben",
  amountLabel: "Betrag",
  whatToDoNext: "Nächste Schritte",
  selfVerify: "Eigenständig prüfen",
  disclaimerPrefix: "Hinweis:",
  disclaimerBody:
    "Diese Analyse wurde durch KI erstellt und dient nur zu Informationszwecken. Sie ist keine Rechts- oder Finanzberatung. Im Zweifel wenden Sie sich vor einer Zahlung an Ihren Notar oder einen Fachmann.",
  checkAnotherButton: "Weiteren Brief prüfen",
  refetching: "Wird in neuer Sprache aktualisiert…",

  // Verdict labels
  verdictLegitimate: "Sieht legitim aus",
  verdictSuspicious: "Etwas stimmt nicht",
  verdictUnclear: "Nicht feststellbar",

  // Confidence labels
  confidenceHigh: "Hohe Konfidenz",
  confidenceMedium: "Mittlere Konfidenz",
  confidenceLow: "Geringe Konfidenz",
};

const translations = { en, de };

export type TranslationKey = keyof typeof en;

export function useT() {
  const { language } = useLanguage();
  return (key: TranslationKey): string => translations[language][key];
}
